import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { rm } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
const { run, runSandboxedVerification, MAX_OUTPUT } = await import("../extensions/development-pipeline/verifier-tools.ts");
const noisy = await run(process.execPath, ["-e", `process.stdout.write("a".repeat(65535) + "🙂")`], process.cwd(), 5000);
assert.equal(noisy.truncated, true);
assert.ok(Buffer.byteLength(noisy.stdout, "utf8") + Buffer.byteLength(noisy.stderr, "utf8") <= MAX_OUTPUT);
assert.equal(noisy.stdout.endsWith("🙂"), false, "partial emoji must be dropped");
assert.equal(noisy.stdout.includes("�"), false, "truncation must not split UTF-8 code points");
const invalid = await run(process.execPath, ["-e", `process.stdout.write(Buffer.alloc(${MAX_OUTPUT}, 0x80))`], process.cwd(), 5000);
assert.equal(invalid.truncated, true, "invalid UTF-8 sanitization must be disclosed");
assert.ok(Buffer.byteLength(invalid.stdout, "utf8") <= MAX_OUTPUT);
assert.ok(invalid.stdout.includes("�"));
const controller = new AbortController();
const started = Date.now();
const pending = run(process.execPath, ["-e", "setTimeout(() => {}, 30000)"], process.cwd(), 30000, controller.signal);
setTimeout(() => controller.abort(), 50);
const cancelled = await pending;
assert.equal(cancelled.cancelled, true);
assert.equal(cancelled.timedOut, false);
const timed = await run(process.execPath, ["-e", "setTimeout(() => {}, 30000)"], process.cwd(), 50);
assert.equal(timed.timedOut, true);
assert.equal(timed.cancelled, false);
assert.ok(Date.now() - started < 3000, "cancellation must finish promptly");

const sourceMarker = path.join(process.cwd(), ".yorishiro-verifier-source-write.tmp");
await rm(sourceMarker, { force: true });
const writableSnapshot = await runSandboxedVerification(process.execPath, ["-e", "require('node:fs').writeFileSync('snapshot-write.tmp', 'ok'); console.log(process.cwd())"], process.cwd(), 10_000);
assert.equal(writableSnapshot.code, 0, writableSnapshot.stdout + writableSnapshot.stderr);
assert.doesNotMatch(writableSnapshot.stdout, new RegExp(`^${process.cwd().replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, "m"), "verification must run in a disposable snapshot");
assert.equal(existsSync(path.join(process.cwd(), "snapshot-write.tmp")), false, "snapshot writes must not reach the source checkout");
const blockedSourceWrite = await runSandboxedVerification(process.execPath, ["-e", `require('node:fs').writeFileSync(${JSON.stringify(sourceMarker)}, 'forbidden')`], process.cwd(), 10_000);
assert.notEqual(blockedSourceWrite.code, 0, "sandbox must block writes to the source checkout");
assert.equal(existsSync(sourceMarker), false);
const npmStartup = await runSandboxedVerification("npm", ["--version"], process.cwd(), 10_000);
assert.equal(npmStartup.code, 0, npmStartup.stdout + npmStartup.stderr);
console.log("verifier output/cancellation/snapshot test passed");
