import assert from "node:assert/strict";
import process from "node:process";
const { run, MAX_OUTPUT } = await import("../extensions/development-pipeline/verifier-tools.ts");
const noisy = await run(process.execPath, ["-e", `process.stdout.write("a".repeat(65535) + "🙂")`], process.cwd(), 5000);
assert.equal(noisy.truncated, true);
assert.ok(Buffer.byteLength(noisy.stdout, "utf8") + Buffer.byteLength(noisy.stderr, "utf8") <= MAX_OUTPUT);
assert.equal(noisy.stdout.endsWith("🙂"), false, "partial emoji must be dropped");
assert.equal(noisy.stdout.includes("�"), false, "truncation must not split UTF-8 code points");
const invalid = await run(process.execPath, ["-e", `process.stdout.write(Buffer.alloc(${MAX_OUTPUT}, 0x80))`], process.cwd(), 5000);
assert.equal(invalid.truncated, true, "invalid UTF-8 sanitization must be disclosed");
assert.ok(Buffer.byteLength(invalid.stdout, "utf8") <= MAX_OUTPUT);
assert.ok(invalid.stdout.includes("�"));
const controller = new AbortController();
const started = Date.now();
const pending = run(process.execPath, ["-e", "setTimeout(() => {}, 30000)"], process.cwd(), 30000, controller.signal);
setTimeout(() => controller.abort(), 50);
const cancelled = await pending;
assert.equal(cancelled.cancelled, true);
assert.equal(cancelled.timedOut, false);
const timed = await run(process.execPath, ["-e", "setTimeout(() => {}, 30000)"], process.cwd(), 50);
assert.equal(timed.timedOut, true);
assert.equal(timed.cancelled, false);
assert.ok(Date.now() - started < 3000, "cancellation must finish promptly");
console.log("verifier output/cancellation test passed");
